spring.application.name=Luvd1s
vaadin.launch-browser=false
server.port=${PORT:8080}
spring.h2.console.enabled=false
spring.datasource.url=jdbc:h2:mem:luvd1s
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.main.lazy-initialization=true